---

name: Test Response Area

runs:
  using: composite
  steps:
    - name: Set up Node
      uses: actions/setup-node@v4
      with:
        node-version: '20.14.0'
        registry-url: 'https://npm.pkg.github.com'
    - name: Install dependencies
      run: yarn install
    - name: Run tests
      run: yarn test
